# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(max_length=20)),
                ('usage', models.TextField()),
                ('code', models.TextField()),
                ('input_output', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(choices=[(0, 'Begginer'), (1, 'Medium'), (2, 'Advanced')], default=0)),
                ('tags', models.TextField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
