# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code',
            new_name='code_text',
        ),
    ]
